name: Build and Test Packages
on: [pull_request, workflow_dispatch]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.13.2"
        run: npm install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - run: |
          yarn install --immutable --immutable-cache
      - run: |
          yarn lint
      - run: |
          yarn build
      - name: "Inspect Storage Layout"
        continue-on-error: false
        id: storage-inspect-check
        run: |
          yarn storage-inspect:check
